export const DEMO_STATES = ['Funded', 'Delivered', 'Disputed']

export const DEMO_BY_STATE = {
  Funded: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Funded',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Seller view',
    showEvidence: false,
    evidence: [],
    actionNote: 'USDC locked. Mark delivered when work is sent.',
    actionNoteTone: 'muted',
    primaryAction: 'Mark delivered',
    secondaryAction: null,
    secondaryTone: 'danger',
  },
  Delivered: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Delivered',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Buyer view',
    showEvidence: false,
    evidence: [],
    actionNote: 'Seller delivered. Release if OK. Dispute if not.',
    actionNoteTone: 'success',
    primaryAction: 'Release 424.2 USDC',
    secondaryAction: 'Open dispute',
    secondaryTone: 'danger',
  },
  Disputed: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Disputed',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Arbiter view',
    showEvidence: true,
    evidence: [
      { label: 'buyer: incomplete brand pages' },
      { label: 'seller: drive/brand-kit-final.zip' },
    ],
    actionNote: 'USDC stays locked until arbiter release or refund.',
    actionNoteTone: 'danger',
    primaryAction: 'Release to seller',
    secondaryAction: 'Refund buyer',
    secondaryTone: 'danger',
  },
}

export const DEMO_HOTSPOTS = [
  {
    id: 'state',
    label: 'State',
    title: 'State',
    body: 'Same status for both wallets. No private side stage.',
  },
  {
    id: 'terms',
    label: 'Terms',
    title: 'Terms',
    body: 'Price, fee, locked amount, delivery window.',
  },
  {
    id: 'parties',
    label: 'Parties',
    title: 'Parties',
    body: 'Buyer and seller wallets fixed at join.',
  },
  {
    id: 'actions',
    label: 'Actions',
    title: 'Actions',
    body: 'Only valid next steps. Dispute stays separate.',
  },
  {
    id: 'buffer',
    label: 'Buffer',
    title: 'Buffer',
    body: '12h after delivery before seller arbiter fallback.',
  },
]
