export const DEMO_STATES = ['Funded', 'Delivered', 'Disputed']

export const DEMO_BY_STATE = {
  Funded: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Funded',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Seller view',
    evidence: [],
    actionNote: 'Escrow is locked. Mark delivered once the work is sent.',
    actionNoteTone: 'muted',
    primaryAction: 'Mark delivered',
    secondaryAction: null,
    secondaryTone: 'danger',
  },
  Delivered: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Delivered',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Buyer view',
    evidence: [
      { label: 'drive/brand-kit-final.zip' },
      { label: 'note: delivered via shared folder' },
    ],
    actionNote: 'Seller marked delivered. Review the work, then release or dispute.',
    actionNoteTone: 'success',
    primaryAction: 'Release 424.2 USDC',
    secondaryAction: 'Open dispute',
    secondaryTone: 'danger',
  },
  Disputed: {
    id: '1042',
    item: 'Brand kit + landing package',
    state: 'Disputed',
    price: '420',
    fee: '4.2',
    total: '424.2',
    locked: '424.2',
    deliveryDays: 5,
    buyer: '0x7a3f…c91e',
    seller: '0x2b88…4d0a',
    roleHint: 'Arbiter view',
    evidence: [
      { label: 'drive/brand-kit-final.zip' },
      { label: 'dispute: incomplete brand pages' },
    ],
    actionNote: 'Funds stay locked. Arbiter can release, refund, or split.',
    actionNoteTone: 'danger',
    primaryAction: 'Release to seller',
    secondaryAction: 'Refund buyer',
    secondaryTone: 'danger',
  },
}

export const DEMO_HOTSPOTS = [
  {
    id: 'state',
    label: 'State',
    title: 'Room state',
    body: 'Everyone sees the same stage. No private side status.',
  },
  {
    id: 'terms',
    label: 'Terms',
    title: 'Money terms',
    body: 'Price, fee, and locked escrow stay visible after the room opens.',
  },
  {
    id: 'parties',
    label: 'Parties',
    title: 'Buyer and seller',
    body: 'Both wallets are fixed in the room so roles stay unambiguous.',
  },
  {
    id: 'actions',
    label: 'Actions',
    title: 'Next action',
    body: 'Only the valid next step is emphasized. Dangerous exits stay separate.',
  },
  {
    id: 'buffer',
    label: 'Buffer',
    title: '12h arbiter buffer',
    body: 'After delivery, a fixed buffer keeps the exit path honest if someone goes silent.',
  },
]
