export const STAGE_LISTINGS = [
  {
    id: 's1',
    role: 'seller',
    category: 'Design',
    title: 'Landing page + CMS handoff',
    price: '380',
    days: 7,
    creator: '0x8c2a…1f90',
    blurb: 'Fixed scope. Opens a seller room when accepted.',
  },
  {
    id: 's2',
    role: 'buyer',
    category: 'Dev',
    title: 'Looking for Arc integration help',
    price: '650',
    days: 10,
    creator: '0x41be…9c22',
    blurb: 'Buyer listing. Seller joins, then escrow funds.',
  },
  {
    id: 's3',
    role: 'seller',
    category: 'Brand',
    title: 'Brand kit + social templates',
    price: '220',
    days: 5,
    creator: '0x7a3f…c91e',
    blurb: 'Package price and delivery days set up front.',
  },
  {
    id: 's4',
    role: 'seller',
    category: 'Audit',
    title: 'Smart contract review (testnet)',
    price: '900',
    days: 4,
    creator: '0x2b88…4d0a',
    blurb: 'Notes attach in-room if the deal disputes.',
  },
]
