export const DEMO_LISTINGS = [
  {
    id: 'm1',
    role: 'seller',
    title: 'Landing page + CMS handoff',
    price: '380',
    days: 7,
    creator: '0x8c2a…1f90',
    tag: 'Design',
  },
  {
    id: 'm2',
    role: 'buyer',
    title: 'Looking for Arc integration help',
    price: '650',
    days: 10,
    creator: '0x41be…9c22',
    tag: 'Dev',
  },
  {
    id: 'm3',
    role: 'seller',
    title: 'Brand kit + social templates',
    price: '220',
    days: 5,
    creator: '0x7a3f…c91e',
    tag: 'Brand',
  },
  {
    id: 'm4',
    role: 'seller',
    title: 'Smart contract review (testnet)',
    price: '900',
    days: 4,
    creator: '0x2b88…4d0a',
    tag: 'Audit',
  },
  {
    id: 'm5',
    role: 'buyer',
    title: 'Need bot + webhook setup',
    price: '175',
    days: 3,
    creator: '0x9de1…70ab',
    tag: 'Ops',
  },
  {
    id: 'm6',
    role: 'seller',
    title: 'Pitch deck rewrite',
    price: '300',
    days: 6,
    creator: '0x55c0…e812',
    tag: 'Writing',
  },
]
